cc_library(
    name = "collection_compare",
    hdrs = ["collection_compare.hpp"],
    srcs = ['collection_compare.cpp'],
    deps = [
        "@fcpp//lib:beautify",
        "@fcpp//lib/coordination:collection",
        "@fcpp//lib/coordination:geometry",
        "@fcpp//lib/coordination:spreading",
    ],
    visibility = [
        '//visibility:public',
    ],
)
