cc_library(
    name = "channel_broadcast",
    hdrs = ["channel_broadcast.hpp"],
    srcs = ['channel_broadcast.cpp'],
    deps = [
        "@fcpp//lib:beautify",
        "@fcpp//lib:coordination",
        "@fcpp//lib:data",
        "//lib:simulation_setup",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = "collection_compare",
    hdrs = ["collection_compare.hpp"],
    srcs = ['collection_compare.cpp'],
    deps = [
        "@fcpp//lib:beautify",
        "@fcpp//lib:coordination",
        "@fcpp//lib:data",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = "simulation_setup",
    hdrs = ["simulation_setup.hpp"],
    srcs = ['simulation_setup.cpp'],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = "spreading_collection",
    hdrs = ["spreading_collection.hpp"],
    srcs = ['spreading_collection.cpp'],
    deps = [
        "@fcpp//lib:beautify",
        "@fcpp//lib:coordination",
        "@fcpp//lib:data",
        "//lib:simulation_setup",
    ],
    visibility = [
        '//visibility:public',
    ],
)
