cc_binary(
    name = "apartment_walk",
    srcs = ["apartment_walk.cpp"],
    deps = [
        "@fcpp//lib:fcpp",
    ],
)

cc_binary(
    name = "channel_broadcast",
    srcs = ["channel_broadcast.cpp"],
    deps = [
        "@fcpp//lib:fcpp",
        "//lib:channel_broadcast",
    ],
)

cc_binary(
    name = "collection_compare",
    srcs = ["collection_compare.cpp"],
    deps = [
        "@fcpp//lib:fcpp",
        "//lib:collection_compare",
    ],
)

cc_binary(
    name = "message_dispatch",
    srcs = ["message_dispatch.cpp"],
    deps = [
        "@fcpp//lib:fcpp",
        "//lib:message_dispatch",
    ],
)

cc_binary(
    name = "spreading_collection_batch",
    srcs = ["spreading_collection_batch.cpp"],
    deps = [
        "//lib:spreading_collection",
    ],
)

cc_binary(
    name = "spreading_collection_gui",
    srcs = ["spreading_collection_gui.cpp"],
    deps = [
        "//lib:spreading_collection",
    ],
)

cc_binary(
    name = "spreading_collection_mpi",
    srcs = ["spreading_collection_mpi.cpp"],
    deps = [
        "//lib:spreading_collection",
    ],
)

cc_binary(
    name = "spreading_collection_run",
    srcs = ["spreading_collection_run.cpp"],
    deps = [
        "//lib:spreading_collection",
    ],
)
