cc_binary(
    name = "channel_broadcast",
    srcs = ["channel_broadcast.cpp"],
    deps = [
        "@fcpp//lib:fcpp",
        "//lib:channel_broadcast",
    ],
)

cc_binary(
    name = "collection_compare",
    srcs = ["collection_compare.cpp"],
    deps = [
        "@fcpp//lib:fcpp",
        "//lib:collection_compare",
    ],
)

cc_binary(
    name = "spreading_collection",
    srcs = ["spreading_collection.cpp"],
    deps = [
        "@fcpp//lib:fcpp",
        "//lib:spreading_collection",
    ],
)
